/** Same labels as gma-mobile-app INTEREST_TAGS */
export const INTEREST_TAG_OPTIONS: { key: string; label: string }[] = [
  { key: "Social Networking", label: "Social Networking" },
  { key: "Cultural & Community Events", label: "Cultural & Community Events" },
  { key: "Creative Arts & Crafts", label: "Creative Arts & Crafts" },
  { key: "Games, Trivia & Bingo", label: "Games, Trivia & Bingo" },
  { key: "Food & Cooking", label: "Food & Cooking" },
  { key: "Music & Karaoke", label: "Music & Karaoke" },
  { key: "Book Club", label: "Book Club" },
  { key: "Theatre & Movies", label: "Theatre & Movies" },
  { key: "Professional Networking", label: "Professional Networking" },
  { key: "Career Development & Info", label: "Career Development & Info" },
  { key: "Entrepreneurship", label: "Entrepreneurship" },
  { key: "Workshops & Skill Share", label: "Workshops & Skill Share" },
  { key: "Mentoring & Coaching", label: "Mentoring & Coaching" },
  { key: "Financial Literacy & Investing", label: "Financial Literacy & Investing" },
  { key: "Gym & Fitness", label: "Gym & Fitness" },
  { key: "Real Estate & Home Ownership", label: "Real Estate & Home Ownership" },
  { key: "Team Sports", label: "Team Sports" },
  { key: "Public Speaking & Communication", label: "Public Speaking & Communication" },
  { key: "Yoga & Pilates", label: "Yoga & Pilates" },
  { key: "Running & Walking", label: "Running & Walking" },
  { key: "Hiking & Outdoor Adventure", label: "Hiking & Outdoor Adventure" },
  { key: "Wellness & Retreats", label: "Wellness & Retreats" },
  { key: "Climbing & Extreme Sports", label: "Climbing & Extreme Sports" },
  { key: "Cycling & Riding", label: "Cycling & Riding" },
  { key: "Healthy Eating", label: "Healthy Eating" },
];
